# Generated by Django 3.2 on 2021-04-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audio',
            field=models.FileField(default='Doc/None/No-audio.wav', upload_to='Doc/'),
        ),
    ]
