# Generated by Django 3.2 on 2021-04-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0004_task_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
    ]
