# Generated by Django 3.2 on 2021-04-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0005_remove_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='audio',
            field=models.FileField(default='Audio/None/No-audio.wav', upload_to='Audio/'),
        ),
    ]
