# Generated by Django 3.2 on 2021-04-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0006_alter_task_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
