# Generated by Django 3.2 on 2021-04-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0007_remove_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_desc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_name',
        ),
    ]
